language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  licenses:
  - ".+"
before_script:
- mkdir -p "${ANDROID_HOME}/licenses"
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "${ANDROID_HOME}/licenses/android-sdk-preview-license"
- echo -e "\nd975f751698a77b662f1254ddbeed3901e976f5a" > "${ANDROID_HOME}/licenses/intel-android-extra-license"
script:
- "./gradlew assembleRelease || true --stacktrace"
before_install:
- mkdir keys
- openssl aes-256-cbc -K $encrypted_70d69dea56b6_key -iv $encrypted_70d69dea56b6_iv
  -in gank_keystore.jks.enc -out keys/gank_keystore.jks -d
- chmod +x gradlew
before_deploy:
- mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/gank.apk
deploy:
  provider: releases
  file: app/build/outputs/apk/gank.apk
  skip_cleanup: true
  api_key:
    secure: "HoZlREBj/w+xLlQiriixrX63gPD8BX6ZTz0d4LSdk00E538orVpHhfq1TqfKU1Aw509r7d8ihIDu8dvPMtXFHz6nF2uJWStVFDx2kSVIQVoLkYnB4D+E/AkOa3sXmxOzv4CwaAN8bhFfRrXv38Erjo8dAUISO+648+9xENYn5Khgofmtdmay37AjbC5iim9lboiZ9QPQZOdzZh+RHzBO+TbTcSq6AaQUlzTWfQBNW8P3dJUTiMSBmAFPqk2BduhM4HqwVz/hKm0Q8KTdFXDpJn3XfuMXGamtKCTCPmWy+roG6l/ejwkjr0/Wzgio8JZGmvjHGfISP7QCsVOCF4/QIJ0+ZGeQnssWUOz2NRtI1zGmejPtVDWnd0yfWRwPL8BvX73I1ycnlehi4RNmteV0YdQ5GB6Ai/UwP6g1Ol48e7tMXuTrnMp/vgvYpKrXwnSDwa4sIKg8q37X2wFHtQCAryFr8WPmu5NvYiHL2g41SUL4tMSXAFCwEcziBQOJdZTiwGa2jiSAvtnub4nIt7N8PKVVKXRbwfyD9QeIOYCY5gBwv5WWmQIlgbEtqD9i+XSEqgLYpJ8UllgVkZ7F96/lasdcy4VTINNmU/OGn87/1ZYjF6AFPPe8LSdyaATV1dG+90JBhg4l7I/pr5T7RS4qI5SPHIz1a6japZOeAFuB7z8="
  on:
    tags: true
cache:
  directories:
  - "$HOME/.m2"
